// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Clip is the predicate function for clip builders.
type Clip func(*sql.Selector)

// Creator is the predicate function for creator builders.
type Creator func(*sql.Selector)
