// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Clip is the predicate function for clip builders.
type Clip func(*sql.Selector)

// Creator is the predicate function for creator builders.
type Creator func(*sql.Selector)

// Emote is the predicate function for emote builders.
type Emote func(*sql.Selector)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)

// Vod is the predicate function for vod builders.
type Vod func(*sql.Selector)
