// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClipsColumns holds the columns for the "clips" table.
	ClipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "duration", Type: field.TypeInt},
		{Name: "date", Type: field.TypeTime},
		{Name: "filename", Type: field.TypeString},
		{Name: "resolution", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt},
		{Name: "view_count", Type: field.TypeInt},
		{Name: "creator_clips", Type: field.TypeInt, Nullable: true},
	}
	// ClipsTable holds the schema information for the "clips" table.
	ClipsTable = &schema.Table{
		Name:       "clips",
		Columns:    ClipsColumns,
		PrimaryKey: []*schema.Column{ClipsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "clips_creators_clips",
				Columns:    []*schema.Column{ClipsColumns[8]},
				RefColumns: []*schema.Column{CreatorsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// CreatorsColumns holds the columns for the "creators" table.
	CreatorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// CreatorsTable holds the schema information for the "creators" table.
	CreatorsTable = &schema.Table{
		Name:       "creators",
		Columns:    CreatorsColumns,
		PrimaryKey: []*schema.Column{CreatorsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClipsTable,
		CreatorsTable,
	}
)

func init() {
	ClipsTable.ForeignKeys[0].RefTable = CreatorsTable
}
