// Code generated by entc, DO NOT EDIT.

package clip

const (
	// Label holds the string label denoting the clip type in the database.
	Label = "clip"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldFilename holds the string denoting the filename field in the database.
	FieldFilename = "filename"
	// FieldResolution holds the string denoting the resolution field in the database.
	FieldResolution = "resolution"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldViewCount holds the string denoting the view_count field in the database.
	FieldViewCount = "view_count"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeVod holds the string denoting the vod edge name in mutations.
	EdgeVod = "vod"
	// EdgeGame holds the string denoting the game edge name in mutations.
	EdgeGame = "game"
	// Table holds the table name of the clip in the database.
	Table = "clips"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "clips"
	// CreatorInverseTable is the table name for the Creator entity.
	// It exists in this package in order to avoid circular dependency with the "creator" package.
	CreatorInverseTable = "creators"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "creator_clips"
	// VodTable is the table that holds the vod relation/edge. The primary key declared below.
	VodTable = "vod_clips"
	// VodInverseTable is the table name for the Vod entity.
	// It exists in this package in order to avoid circular dependency with the "vod" package.
	VodInverseTable = "vods"
	// GameTable is the table that holds the game relation/edge.
	GameTable = "games"
	// GameInverseTable is the table name for the Game entity.
	// It exists in this package in order to avoid circular dependency with the "game" package.
	GameInverseTable = "games"
	// GameColumn is the table column denoting the game relation/edge.
	GameColumn = "clip_game"
)

// Columns holds all SQL columns for clip fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDuration,
	FieldDate,
	FieldFilename,
	FieldResolution,
	FieldSize,
	FieldViewCount,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "clips"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"creator_clips",
}

var (
	// VodPrimaryKey and VodColumn2 are the table columns denoting the
	// primary key for the vod relation (M2M).
	VodPrimaryKey = []string{"vod_id", "clip_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DurationValidator is a validator for the "duration" field. It is called by the builders before save.
	DurationValidator func(int) error
	// FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	FilenameValidator func(string) error
)
