// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/AgileProggers/archiv-backend-go/pkg/ent/creator"
)

// Creator is the model entity for the Creator schema.
type Creator struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CreatorQuery when eager-loading is set.
	Edges CreatorEdges `json:"edges"`
}

// CreatorEdges holds the relations/edges for other nodes in the graph.
type CreatorEdges struct {
	// Clips holds the value of the clips edge.
	Clips []*Clip `json:"clips,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ClipsOrErr returns the Clips value or an error if the edge
// was not loaded in eager-loading.
func (e CreatorEdges) ClipsOrErr() ([]*Clip, error) {
	if e.loadedTypes[0] {
		return e.Clips, nil
	}
	return nil, &NotLoadedError{edge: "clips"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Creator) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case creator.FieldID:
			values[i] = new(sql.NullInt64)
		case creator.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Creator", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Creator fields.
func (c *Creator) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case creator.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case creator.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		}
	}
	return nil
}

// QueryClips queries the "clips" edge of the Creator entity.
func (c *Creator) QueryClips() *ClipQuery {
	return (&CreatorClient{config: c.config}).QueryClips(c)
}

// Update returns a builder for updating this Creator.
// Note that you need to call Creator.Unwrap() before calling this method if this Creator
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Creator) Update() *CreatorUpdateOne {
	return (&CreatorClient{config: c.config}).UpdateOne(c)
}

// Unwrap unwraps the Creator entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Creator) Unwrap() *Creator {
	tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Creator is not a transactional entity")
	}
	c.config.driver = tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Creator) String() string {
	var builder strings.Builder
	builder.WriteString("Creator(")
	builder.WriteString(fmt.Sprintf("id=%v", c.ID))
	builder.WriteString(", name=")
	builder.WriteString(c.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Creators is a parsable slice of Creator.
type Creators []*Creator

func (c Creators) config(cfg config) {
	for _i := range c {
		c[_i].config = cfg
	}
}
