// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/AgileProggers/archiv-backend-go/pkg/ent/emote"
	"github.com/AgileProggers/archiv-backend-go/pkg/ent/provider"
)

// Emote is the model entity for the Emote schema.
type Emote struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmoteQuery when eager-loading is set.
	Edges           EmoteEdges `json:"edges"`
	provider_emotes *int
}

// EmoteEdges holds the relations/edges for other nodes in the graph.
type EmoteEdges struct {
	// Provider holds the value of the provider edge.
	Provider *Provider `json:"provider,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmoteEdges) ProviderOrErr() (*Provider, error) {
	if e.loadedTypes[0] {
		if e.Provider == nil {
			// The edge provider was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: provider.Label}
		}
		return e.Provider, nil
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Emote) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case emote.FieldID:
			values[i] = new(sql.NullInt64)
		case emote.FieldName, emote.FieldURL:
			values[i] = new(sql.NullString)
		case emote.ForeignKeys[0]: // provider_emotes
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Emote", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Emote fields.
func (e *Emote) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case emote.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			e.ID = int(value.Int64)
		case emote.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				e.Name = value.String
			}
		case emote.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				e.URL = value.String
			}
		case emote.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field provider_emotes", value)
			} else if value.Valid {
				e.provider_emotes = new(int)
				*e.provider_emotes = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryProvider queries the "provider" edge of the Emote entity.
func (e *Emote) QueryProvider() *ProviderQuery {
	return (&EmoteClient{config: e.config}).QueryProvider(e)
}

// Update returns a builder for updating this Emote.
// Note that you need to call Emote.Unwrap() before calling this method if this Emote
// was returned from a transaction, and the transaction was committed or rolled back.
func (e *Emote) Update() *EmoteUpdateOne {
	return (&EmoteClient{config: e.config}).UpdateOne(e)
}

// Unwrap unwraps the Emote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (e *Emote) Unwrap() *Emote {
	tx, ok := e.config.driver.(*txDriver)
	if !ok {
		panic("ent: Emote is not a transactional entity")
	}
	e.config.driver = tx.drv
	return e
}

// String implements the fmt.Stringer.
func (e *Emote) String() string {
	var builder strings.Builder
	builder.WriteString("Emote(")
	builder.WriteString(fmt.Sprintf("id=%v", e.ID))
	builder.WriteString(", name=")
	builder.WriteString(e.Name)
	builder.WriteString(", url=")
	builder.WriteString(e.URL)
	builder.WriteByte(')')
	return builder.String()
}

// Emotes is a parsable slice of Emote.
type Emotes []*Emote

func (e Emotes) config(cfg config) {
	for _i := range e {
		e[_i].config = cfg
	}
}
