definitions:
  main.vod:
    properties:
      bitrate:
        type: number
      date:
        type: string
      duration:
        type: integer
      filename:
        type: string
      fps:
        type: number
      id:
        type: string
      publish:
        type: boolean
      resolution:
        type: string
      size:
        type: integer
      title:
        type: string
    required:
    - date
    - duration
    - filename
    - fps
    - id
    - publish
    - resolution
    - size
    - title
    type: object
info:
  contact: {}
paths:
  /vods/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.vod'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get all vods
      tags:
      - Vods
    post:
      consumes:
      - application/json
      parameters:
      - description: Vod dict
        in: body
        name: Body
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create vod
      tags:
      - Vods
  /vods/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Unique Identifier
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.vod'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get vod by id
      tags:
      - Vods
swagger: "2.0"
