definitions:
  models.Clip:
    properties:
      creator:
        type: integer
      date:
        type: string
      duration:
        type: integer
      filename:
        type: string
      game:
        type: integer
      resolution:
        type: string
      size:
        type: integer
      title:
        type: string
      uuid:
        type: string
      viewcount:
        type: integer
      vod:
        type: string
    required:
    - date
    - duration
    - filename
    - resolution
    - size
    - title
    - viewcount
    type: object
  models.Creator:
    properties:
      clips:
        items:
          $ref: '#/definitions/models.Clip'
        type: array
      name:
        type: string
      uuid:
        type: integer
    required:
    - name
    type: object
  models.Game:
    properties:
      box_art:
        type: string
      name:
        type: string
      uuid:
        type: integer
    required:
    - box_art
    - name
    type: object
  models.Vod:
    properties:
      clips:
        items:
          $ref: '#/definitions/models.Clip'
        type: array
      date:
        type: string
      duration:
        type: integer
      filename:
        type: string
      fps:
        type: number
      publish:
        type: boolean
      resolution:
        type: string
      size:
        type: integer
      title:
        type: string
      uuid:
        type: string
    required:
    - date
    - duration
    - filename
    - fps
    - publish
    - resolution
    - size
    - title
    type: object
info:
  contact: {}
paths:
  /clips/:
    get:
      consumes:
      - application/json
      parameters:
      - description: The uuid of a clip
        in: query
        name: uuid
        type: string
      - description: The title of a clip
        in: query
        name: title
        type: string
      - description: The duration of a clip
        in: query
        name: duration
        type: integer
      - description: The date of a clip
        in: query
        name: date
        type: string
      - description: The filename of a clip
        in: query
        name: filename
        type: string
      - description: The resolution of a clip
        in: query
        name: resolution
        type: string
      - description: The size of a clip
        in: query
        name: size
        type: integer
      - description: The viewcount of a clip
        in: query
        name: viewcount
        type: integer
      - description: The creator id of a clip
        in: query
        name: creator
        type: integer
      - description: The game id of a clip
        in: query
        name: game
        type: integer
      - description: The vod id of a clip
        in: query
        name: vod
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Clip'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get all clips
      tags:
      - Clips
    post:
      consumes:
      - application/json
      parameters:
      - description: Clip dict
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.Clip'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create clip
      tags:
      - Clips
  /clips/{uuid}:
    get:
      parameters:
      - description: Unique Identifier
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Clip'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get clips by uuid
      tags:
      - Clips
  /creators/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Creator'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get all creators
      tags:
      - Creators
    post:
      consumes:
      - application/json
      parameters:
      - description: Creator dict
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.Creator'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create creator
      tags:
      - Creators
  /creators/{uuid}:
    get:
      parameters:
      - description: Unique Identifyer
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Creator'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get creator by uuid
      tags:
      - Creators
  /games/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Game'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get all games
      tags:
      - Games
    post:
      consumes:
      - application/json
      parameters:
      - description: Game dict
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.Game'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create game
      tags:
      - Games
  /games/{uuid}:
    get:
      parameters:
      - description: Unique Identifier
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Game'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get game by uuid
      tags:
      - Games
  /vods/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Vod'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get all vods
      tags:
      - Vods
    post:
      consumes:
      - application/json
      parameters:
      - description: Vod dict
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/models.Vod'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create vod
      tags:
      - Vods
  /vods/{uuid}:
    get:
      parameters:
      - description: Unique Identifier
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Vod'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get vod by uuid
      tags:
      - Vods
swagger: "2.0"
